set_delayed_charging:
  fields:
    device_id:
      selector:
        device:
          integration: blue_current
      required: true
    expected_departure_time:
      selector:
        time:
      required: true
    expected_charging_session_size:
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: kWh
          mode: box
      required: true
    immediately_charge:
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: kWh
          mode: box
      required: true

set_price_based_charging:
  fields:
    device_id:
      selector:
        device:
          integration: blue_current
      required: true
    days:
      selector:
        select:
          translation_key: days
          options:
            - monday
            - tuesday
            - wednesday
            - thursday
            - friday
            - saturday
            - sunday
          multiple: true
      required: true
    start_time:
      selector:
        time:
      required: true
    end_time:
      selector:
        time:
      required: true
